title: "Navin Kartik"
email: "nkartik@gmail.com"
description: >- 
  Personal academic homepage for Navin Kartik, economist.
baseurl: ""
url: "https://navinkartik.github.io"
theme: minima

markdown: kramdown
plugins:
  - jekyll-feed

collections:
  pages:
    output: true
